//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class characteristics_values
    {
        public int id { get; set; }
        public string name { get; set; }
        public int value { get; set; }
        public int c_header_id_id { get; set; }
    }
}
