//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HrsEntities : DbContext
    {
        public HrsEntities()
            : base("name=HrsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appellation> appellation { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<characteristics_headers> characteristics_headers { get; set; }
        public virtual DbSet<characteristics_values> characteristics_values { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<expert_product_characteristic> expert_product_characteristic { get; set; }
        public virtual DbSet<expert_rates> expert_rates { get; set; }
        public virtual DbSet<experts> experts { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<regions> regions { get; set; }
        public virtual DbSet<star_ratings_rating> star_ratings_rating { get; set; }
        public virtual DbSet<star_ratings_userrating> star_ratings_userrating { get; set; }
        public virtual DbSet<user_rates> user_rates { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<vendors> vendors { get; set; }
    }
}
