//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.inventory = new HashSet<inventory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string photo_path { get; set; }
        public int appellation_id_id { get; set; }
        public int category_id_id { get; set; }
        public int vendor_id_id { get; set; }
    
        public virtual vendors vendors { get; set; }
        public virtual categories categories { get; set; }
        public virtual appellation appellation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventory { get; set; }
    }
}
