//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class star_ratings_userrating
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string ip { get; set; }
        public int score { get; set; }
        public int rating_id { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
