//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class star_ratings_rating
    {
        public int id { get; set; }
        public int count { get; set; }
        public int total { get; set; }
        public decimal average { get; set; }
        public Nullable<int> object_id { get; set; }
        public Nullable<int> content_type_id { get; set; }
    }
}
