# Generated by Django 2.0.6 on 2018-06-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'appellation',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Characteristics_headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'characteristics_headers',
            },
        ),
        migrations.CreateModel(
            name='Characteristics_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.IntegerField(default=0)),
                ('c_header_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Characteristics_headers')),
            ],
            options={
                'db_table': 'characteristics_values',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Expert_product_characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_values', models.IntegerField(default=0)),
                ('c_header_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Characteristics_headers')),
            ],
            options={
                'db_table': 'expert_product_characteristic',
            },
        ),
        migrations.CreateModel(
            name='Expert_rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'expert_rates',
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('avatar', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'db_table': 'experts',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('photo_path', models.TextField()),
                ('appellation_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Appellation')),
                ('category_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Countries')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='User_rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Products')),
            ],
            options={
                'db_table': 'user_rates',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('avatar', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('region_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Regions')),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.AddField(
            model_name='user_rates',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Users'),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Vendors'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Products'),
        ),
        migrations.AddField(
            model_name='expert_rates',
            name='expert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Experts'),
        ),
        migrations.AddField(
            model_name='expert_rates',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Products'),
        ),
        migrations.AddField(
            model_name='expert_product_characteristic',
            name='expert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Experts'),
        ),
        migrations.AddField(
            model_name='expert_product_characteristic',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Products'),
        ),
        migrations.AddField(
            model_name='appellation',
            name='region_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Regions'),
        ),
    ]
