# Generated by Django 2.0.6 on 2018-06-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0002_auto_20180626_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='country_id',
        ),
        migrations.AddField(
            model_name='regions',
            name='country_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hrsapp.Countries'),
        ),
    ]
