# Generated by Django 2.0.6 on 2018-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0003_auto_20180626_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12.95, max_digits=6),
        ),
    ]
