# Generated by Django 2.0.6 on 2018-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0004_inventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
